# src/templates.py

LATEX_COVER_LETTER = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{xcolor}

% MARGINS (Standard European A4)
\geometry{top=2.5cm, bottom=2.5cm, left=2.5cm, right=2.5cm}

% FONT (Clean, Academic)
\usepackage{lmodern}

\begin{document}
\pagestyle{empty}

% --- HEADER (Your Info) ---
\begin{flushright}
    \textbf{Abhiram Radha Krishna}\\
    Stuttgart, Germany\\
    \today
\end{flushright}

\vspace{1cm}

% --- RECIPIENT ---
\noindent
\textbf{To the Selection Committee / Prof. [NAME]}\\
\textit{{university_name}}\\
{department_name}

\vspace{0.5cm}

% --- SUBJECT LINE ---
\noindent
\textbf{Subject: Application for PhD Position in {job_title}}

\vspace{0.5cm}

% --- SALUTATION ---
\noindent
Dear Prof. [Last Name] / Selection Committee,

\vspace{0.5cm}

% --- BODY (Generated by Mikasa) ---
{body_content}

\vspace{1cm}

% --- SIGN-OFF ---
\noindent
Yours sincerely,

\vspace{0.5cm}

% --- SIGNATURE IMAGE ---
% Uncomment the line below if you have signature.png in the same folder
% \includegraphics[width=4cm]{signature.png}

\vspace{0.2cm}

\noindent
\textbf{Abhiram Radha Krishna}

\end{document}
"""